/**:
  ros__parameters:
    angular_velocity_offset_x: 0.1    # [rad/s] def0.0
    angular_velocity_offset_y: 0.1    # [rad/s] def0.0
    angular_velocity_offset_z: 0.1    # [rad/s] def0.0
    angular_velocity_stddev_xx: 0.1  # [rad/s] def0.03
    angular_velocity_stddev_yy: 0.1  # [rad/s] def0.03
    angular_velocity_stddev_zz: 0.1  # [rad/s] def0.03
